export default {
  common: {
    Back: 'Back',
    HomeTite: 'Yun Ping Tai',
    AddClass: 'New Class',
    Keep: 'Keep',
    Logout: 'Logout',
    Login: 'Login',
    Saving: 'Saving',
    Info: 'Info',
    Exception_occurred: 'Exception occurred',
    ClassName: 'Class Name',
    CoverClass: 'Cover of class',
    EntryClass: 'Please Entry Class',
    Class: 'Class',
    Curriculum: 'Curriculum',
    UnknownClass: 'Unknown Class',
    My: 'My',
    No_files: 'No Files',
    Please_entry: 'Please Entry',
    Title: 'Title',
    Url: 'Url',
    Sign: 'Sign',
    Person: 'Person',
    Total: 'Total',
    Click: 'click',
    Loading: 'Loading...',
    PleaseAwait: 'Please look forward to it.',
    Add: 'Create',
    Submit: 'Submit',
    Drop_down_refresh: 'Drop down refresh',
    Pull_up_Load: 'Pull up Load',
    End: 'End',
    Delete: 'Delete',
    Strat: 'Strat',
    Edit: 'Edit',
    Curbanke: {
      name: 'Unknown Class',
      avatar: ""
    },
    Teacher: 'Teacher',
    Student: 'Student',
    Tourist: 'Tourist',
    Front: 'Front',
    Month: 'Month',
    Day: 'Day',
    Hour: 'Hour',
    min: 'min',
    second: 'second',
    Whole: 'Whole',
    Close: 'Close',
  },
  bankeZiYuan: {
    Upload_files: 'Upload files',
    WebLink: 'Web links',
    Resources_storehouse: 'Resources storehouse',
    Resources: 'Resources',
    Member: 'Member',
    Task: 'Task',
    Interaction: 'Interaction',
    Details: 'Details',
  },
  bankeMember: {
    Plan: 'Plan',
  },
  bankeTask: {
    No_task: 'No task',
    AddTask: 'Add task',
    Have_in_hand: 'Have in hand',
    Has_ended: 'Has ended',
    Not_yet_begun: 'Not yet begun',
    Already_involved: 'Already involved',
    Not_participate: 'Not participate',
    Partake: 'Partake',
    Job_Results: 'Job Results',
    Job_details: 'Job details',
    Submit_job: 'Submit job',
    Assignment_score: 'Assignment score',
    Score_of_the_operation_owner: 'Score of the operation owner',
    Answer: 'Answer',
    My_submission: 'My submission',
    No_score: 'No score',
    Not_yet: 'Not yet',
    Submitted: 'Submitted',
    To_submit: 'To submit',
    Comment_area: 'Comment area',
    To: 'To',
    Score: 'Score',
    Overall_score: 'Overall score',
    Full_marks: 'Full marks',
    Task_Answer: 'Task Answer',
    All_submitted: 'All submitted',
    No_answer_set: 'No answer set',
    No_score_yet: 'No score yet',
    No_submission: 'No submission',
    Unlimited_submission_time: 'Unlimited submission time',
    Allow_timeout_submission: 'Allow timeout submission',
    Timeout_submission_not_allowed: 'Timeout submission not allowed',
    No_participants: 'No participants',
    All_submitteds: 'All submitted',
    Not_submitted: 'Not submitted',

    //附加组件
    Enclosure: 'Enclosure',
    Enter_details: 'Enter details',
    Add_Enclosure: 'Add Enclosure',
    Wait_uploading: 'Wait uploading',
    Upload_failure: 'Upload failure',
    Delete_file: 'Delete file',
    //所有人得分page
    State_tips_text: 'The activity is not over yet, the following score may not be the final score',
    //信息page
    Create_time: 'Create time',
    Last_start_time: 'Last start time',
    First_time_submission: 'First time submission',
    Job_not_submitted: 'Job not submitted',
  },
  bankehHudong: {
    Start_class_time: 'Start class time',
    End_class_time: 'End class time',
    Sign_time: 'Sign time',
    see_all_class_history: 'View all class records',
    All_class_records: 'All class records',
    No_class_record: 'No class record ',
    No_student_sign_in_record: 'No student sign in record',
    All_students_records: 'Class records of all students',
    ClassOver: 'Class is over',
    ClassOverEd: 'Class has been dismissed',
    BeginsClass: 'Class begins',
    No_classes_currently_open: 'No classes currently open',
    Currently_started: 'Currently started',
    Class_is_now_over: 'Class is now over',
    SignSuccessfully: 'Sign in successfully',
    LateInfo: "You're late",
    SignTimeOver: "It's past the check-in time",
    No_classes_at_present: 'No classes at present',
    CheckIn: 'Check-in',
    No_sign_in: 'No sign in',
    Late: 'Late',
    Overtime: 'Over time',
  },
  bankeXingQing: {
    EditClass: 'Edit Class',
    EndingClass: 'Ending Class',
    DeleteClass: 'Delete Class',
  },
  personal: {
    Account: 'Account',
    Set_up: 'Set up',
    About: 'About',
    Personal_information: 'Personal information',
    Head_portrait: 'Head portrait',
    Nickname: 'Nickname',
    Role: 'Role',
    Edit_head: "Editor's head",
    Nickname_entry: 'Fill in your nickname',
    Nickname_tips: 'Set your personal nickname',
  },
  Indicator: {
    Saving: 'Saving...',
    Loading: 'Loading...',
    Uploading: 'Uploading...',
    Processing: 'Processing...',
    Committing: 'Committing...',
    Logon: 'Logon...',
    Set_up: 'Set up...',
  },
  confirm: {
    Tips: 'Tips',
    Ok: 'Ok',
    Cancel: 'Cancel',
    Success: 'Success',
    BeginsClass: 'Are you sure you want to have class',
    ClassOver: 'Are you sure you want to finish class',
    SignOver: 'Are you sure you want to sign in',
    Exit_current_account: 'Are you sure you Exit current account'
  },
  btnlist: [{
      name: 'Whole'
    },
    {
      name: 'Ongoing'
    },
    {
      name: 'Complete'
    }
  ],
  btnlist2: [{
      name: 'Whole'
    },
    {
      name: 'Started'
    },
    {
      name: 'Ongoing'
    },
    {
      name: 'Complete'
    }
  ],
  langs: [{
      name: 'Chinese',
      langType: 'zh'
    },
    {
      name: 'English',
      langType: 'en'
    },
  ]
}